#!/bin/bash

# Find out local directory; can't be abstracted as for that we'd need to know the local directory!
# Taken from http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  SCRIPT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$SCRIPT/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
# END

cp $SCRIPT/scripts/git-hooks-pre-commit .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
