#!/bin/bash

# Find out local directory; can't be abstracted as for that we'd need to know the local directory!
# Taken from http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  SCRIPT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$SCRIPT/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
# END

DIR=$1
NAME=$2

# If we are using a remote server we need the trailing colon for copy operations
if [ $# -eq 3 ]; then
	HOST=$3':'
else
	HOST=''
	mkdir $HOST$DIR
fi

# Confirms the directory we're copying to
echo $HOST$DIR

# Copy everything
scp -rp . $HOST$DIR
# Copy our git files to new locations in the remote .git directory
scp -rp $SCRIPT/scripts/git-remote-config $HOST$DIR/.git/config
scp -rp $SCRIPT/scripts/git-hooks-post-update $HOST$DIR/.git/hooks/post-update

# If we're working on a networked server we need to run this command by SSH
if [ $# -eq 3 ]; then
	ssh $3 chmod +x $DIR/.git/hooks/post-update
else
	chmod +x $DIR/.git/hooks/post-update
fi

# Add the remote using git bash
git remote add $NAME $HOST$DIR/.git